---
title: "Manip ADAAPT"
author: "David Chassagnaud"
date: "`r Sys.Date()`"
format:
  html:
    theme: united      # Tu peux changer le thème : cosmo, flatly, united, etc.
    highlight-style: pygments  # ← ou github, monokai, pygments, etc.
    toc: true         # Active la table des matières
    toc-depth: 2      # Niveau de profondeur de la table des matières (1 à 6)
    toc-location: right  # Position : left, right ou float
    number-sections: true  # Numérote les sections
    code-fold: true   # Permet de replier/déplier les blocs de code
    code-tools: true  # Affiche les outils (copier le code, etc.)
    smooth-scroll: true  # Ajoute un défilement fluide
    page-layout: full
    fig-width: 12 # Pour gèrer la taille des figure par défaut 
    fig-height: 9
    fig-align: center # Alignement des figures par défaut 
  #  include-after-body: footer.html # préciser le chemin du fichier(mis dans qmd)
   # css: style.css # préciser le chemin du fichier(mis dans qmd)
editor_options: 
  chunk_output_type: console
---

Manip ADAAPT ...

# Packages
```{r packages, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(writexl)
library(readxl)

```

# Import JDD
```{r Import JDD, message=FALSE, warning=FALSE}
# Import
hauteur <- read_excel("~/Desktop/Adaapt/Mesures/hauteur.xlsx")


# Chargement et mise en forme
hauteur <- read_excel("~/Desktop/Adaapt/Mesures/hauteur.xlsx") %>%
  drop_na() %>%  # Supprime d'abord les lignes incomplètes
  mutate(
    across(-hauteur_05_05, as.factor),         # Transforme toutes les autres colonnes en facteurs
    hauteur_05_05 = as.numeric(hauteur_05_05)  # Convertit hauteur_05_05 en numérique
  )

# Vérification de la structure
str(hauteur)

```

# Visualisation Hauteur
```{r Visualisation, message=FALSE, warning=FALSE}

library(ggplot2)

ggplot(hauteur, aes(x = geno, y = hauteur_05_05)) +
  geom_boxplot(fill = "skyblue") +
  theme_minimal() +
  labs(title = "Hauteur par génotype", x = "Génotype", y = "Hauteur (05/05)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```







